name: azul_movies
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.1+1
  custom_navigator: ^0.3.0
  font_awesome_flutter: ^8.10.1
  carousel_slider: ^2.3.1
  cached_network_image: ^2.4.1
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+3
  flutter_svg: ^0.19.2+1
  readmore: ^1.0.1
  modal_bottom_sheet: ^1.0.0+1
  intl: ^0.16.1
  date_picker_timeline: ^1.2.1
  flutter_spinkit: ^4.1.2+1
  top_snackbar_flutter: ^0.0.3

  #stream video
  iqplayer: ^0.4.0
  flutter_simple_video_player: ^0.0.9
  url_launcher: ^5.7.10
  share: ^0.6.5+4

  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  platform_device_id: ^0.1.3
  package_info: ^0.4.3+2

  #Firebase
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/changa/Changa-Bold.ttf
        - asset: assets/fonts/changa/Changa-ExtraBold.ttf
        - asset: assets/fonts/changa/Changa-ExtraLight.ttf
        - asset: assets/fonts/changa/Changa-Light.ttf
        - asset: assets/fonts/changa/Changa-Medium.ttf
        - asset: assets/fonts/changa/Changa-Regular.ttf
        - asset: assets/fonts/changa/Changa-SemiBold.ttf
          style: italic
